spring.application.name=xushu-claude
logging.threshold.console= ERROR

spring.ai.deepseek.api-key= ${DEEPSEEK_API_KEY}
spring.ai.deepseek.chat.model= qwen3.7-max
spring.ai.deepseek.chat.base-url= https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1

logging.level.org.springframework.ai.chat.client.advisor= DEBUG

spring.ai.mcp.client.stdio.servers-configuration= classpath:/mcp/mcp-servers-config.json

